### ISSUE TITLE
Add --reindex option

### ISSUE THREAD

**Issue by strophy** [dashevo/platform#103]
## Expected Behavior

Sometimes it is necessary to start dashd with the `--reindex` option (e.g. if the chain is corrupt or new addresses were added). It should be possible to add a flag to the `dashmate start` command to achieve this.

## Current Behavior

Currently this can be achieved with a workaround by editing `templates/core/dash.conf.dot` and adding `reindex=1` there, then removing it again.

## Possible Solution

Use a flag and add conditional login in the `dash.conf.dot` template.

**Comment by pshenmic** [comment]
https://github.com/dashevo/platform/pull/533
