### ISSUE TITLE
platform.identities.register() throws Error: InstantLock waiting period for transaction ... timed out

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#158]
Using the latest dashmate from npm and running `dashmate update` for the latest docker images, I can no longer register an identity, I always get the error:

`Error: InstantLock waiting period for transaction 6f4f9662efe18a0e0bce376964f875cb664f7101ecca2d1236d6075bb3ba7134 timed out`

This blocks all local development using dashmate. I get the same error on testnet but only occasionally, using dashmate the error throws every time.

**Comment by dashameter** [comment]
When providing the wallet with additional inputs, this error may throw instead:

`InvalidRequestError: Transaction is rejected: tx-txlock-conflict (code 16)`

**Comment by dashameter** [comment]
updated dashmate via npm to `0.21.6-test.2`, still throwing error:
`Error: InstantLock waiting period for transaction c7d76415ae8952756a054d1f85391f9c87cc4523e6177a08cc67ba3086de89d0 timed out
`

**Comment by dashameter** [comment]
tried mono repo dashmate as requested by @shumkov, still throwing error:

`Error: InstantLock waiting period for transaction ff8dd554085e7687510b672531187872cf9e0275c9c6fa95cd598036558690d1 timed out`

**Comment by markin-io** [comment]
@dashameter please retest

**Comment by dashameter** [comment]
retest passed
