### ISSUE TITLE
Dash.org developer page links to deprecated SDK

### ISSUE THREAD

**Issue by coolaj86** [dashevo/platform#166]
https://www.dash.org/platform/ links to https://github.com/dashevo/js-dash-sdk

<img width="687" alt="Screen Shot 2021-12-28 at 11 24 39 PM" src="https://user-images.githubusercontent.com/122831/147633244-649e6848-98fa-43e4-9211-e815683080b2.png">

**Comment by thephez** [comment]
This and several related links were updated last week.
