### ISSUE TITLE
wallet-lib: getTransactionHistory type missing on Account

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#202]
wallet-lib supports transactionHistory now, but the type is missing on Account:

`Property 'getTransactionHistory' does not exist on type 'Account'.`

**Comment by dash-maverick** [comment]
please retest that

**Comment by dashameter** [comment]
retest failed on sdk v3.21.8

![image](https://user-images.githubusercontent.com/57665975/157865254-acd9e67f-e5cc-4f7a-81b7-d9778153bcd4.png)

**Comment by dash-maverick** [comment]
please try it out with v22

**Comment by dashameter** [comment]
retest passed
