### ISSUE TITLE
Error: Invalid instant lock proof signature

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#204]
sdk 3.21.7 on dashmate sometimes throws:

`Error: Invalid instant lock proof signature`

upon identity creation

**Comment by dash-maverick** [comment]
Could you check logs from DAPI docker containers of Dashmate? If there are errors - please bring them here. There must be 6 containers, please check all of them.

**Comment by dash-maverick** [comment]
seems the same as https://github.com/dashevo/platform/issues/92 (being the previous https://github.com/dashevo/dashmate/issues/460)
maybe we should close this new one, huh?

**Comment by dashameter** [comment]
duplicate of #92
