### ISSUE TITLE
Account.getTransactionHistory: unconfirmed time `-1` sorts as oldest tx

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#205]
Timestamp `-1` for unconfirmed txs sorts most recent transaction as the oldest one, suggest using `9999999999` instead

**Comment by SamKirby22** [comment]
@dashameter can you run the released sdk in the tests once the new branch has been released and close if no issues?

**Comment by dashameter** [comment]
> @dashameter can you run the released sdk in the tests once the new branch has been released and close if no issues?

will retest once released in the next sdk version

**Comment by markin-io** [comment]
> > @dashameter can you run the released sdk in the tests once the new branch has been released and close if no issues?
> 
> will retest once released in the next sdk version

Please retest with SDK v3.21.8

**Comment by dashameter** [comment]
retest passed
