### ISSUE TITLE
getTransactionHistory() doesn't show sent txs 95% of the times

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#207]
sent txs don't show up 95% of the time in getTransactionHistory(), sometimes re-init of the wallet helps, but usually it doesn't

**Comment by dash-maverick** [comment]
moved to the backlog, thank you

**Comment by markin-io** [comment]
@dashameter can you please provide a mnemonic for that?

**Comment by markin-io** [comment]
@dashameter please retest with SDK v3.21.8

**Comment by dashameter** [comment]
retest passed, thanks guys !
