### ISSUE TITLE
getTransactionHistory() reports the wrong unix epoch, it is two days in the future: `1642830567` instead of `1642704529`

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#213]
wallet-lib:

getTransactionHistory() reports the wrong unix epoch, it is two days in the future: `1642830567` instead of `1642704529`

also the entire SDK serves time as a javascript date object, suggested that getTransactionHistory() also serves date objects for consistency

**Comment by dash-maverick** [comment]
could you possibly write a pull request for that change ?

**Comment by dashameter** [comment]
@shumkov is it possible that this is a problem with the time being incorrectly set in one of the dashmate docker containers? I can't verify it by testing on testnet because of https://github.com/dashevo/platform/issues/245 I can't create addresses

**Comment by shumkov** [comment]
Is would be nice you provide more details. For example, what network do you use.

For local network, we use mock time to speed up block mining. This can easily push block time to future. You can easily fix that,  changing block mining interval back to 2.5 minutes (default).

**Comment by dash-maverick** [comment]
please retest @dashameter

**Comment by dashameter** [comment]
retest passed on dashmate with 2.5min block time interval
