### ISSUE TITLE
Account.getTransactionHistory(): All inputs and outputs should have a  property `"isMine": true|false` 

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#214]
wallet-lib:

Account.getTransactionHistory(): All inputs and outputs should have a  property `"isMine": true|false` to indicate if the private key for that vin/vout is in the wallets keychain

**Comment by dash-maverick** [comment]
what is the real use case for this along with https://github.com/dashevo/platform/issues/216 ?

**Comment by dash-maverick** [comment]
a precondition would be to fix https://github.com/dashevo/platform/issues/207 (which as we discussed earlier will be researched by the Team)

**Comment by dash-maverick** [comment]
a PR for that has been merged https://github.com/dashevo/platform/pull/319 , please have a look and eventually close

**Comment by dash-maverick** [comment]
please wait until Platform v0.22.2

**Comment by SamKirby22** [comment]
Fix/retest pending Platform release v22.3

**Comment by markin-io** [comment]
Please retest with SDK v3.22.3.
We introduced `addressType` field which can cover your needs for `isMine` true|false functionality.

**Comment by SamKirby22** [comment]
Retest blocked due to new Dashmate issue [to be raised]
