### ISSUE TITLE
Account.getTransactionHistory():  Dash  sent to myself (`.getUnusedAddress().address)`) show as `received` instead of `address_transfer`

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#215]
wallet-lib:

  Account.getTransactionHistory():  Dash  sent to myself (`.getUnusedAddress().address)`) show as `received` instead of `address_transfer`

**Comment by dash-maverick** [comment]
please provide some more details - package version, dashmate (local) / testnet etc. thanks

**Comment by dashameter** [comment]
retest passed dashmate@.22.12
