### ISSUE TITLE
Account.getTransactionHistory():   Needs a property `totalSatoshisTransferred`

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#216]
wallet-lib:

Account.getTransactionHistory():   Needs a property `totalSatoshisTransferred` which is a sum of all  input and output `satoshis`with the `isMine === true`property. How many satoshis did effectively leave or enter my wallet.

**Comment by dash-maverick** [comment]
I guess that `totalDuffsTransferred` instead of `totalSatoshisTransferred`

**Comment by dash-maverick** [comment]
a PR for that has been merged https://github.com/dashevo/platform/pull/319 , please have a look and eventually close

**Comment by SamKirby22** [comment]
Fix/retest pending Platform release v22.3

**Comment by markin-io** [comment]
Please retest with SDK v3.22.3.
We introduced `satoshisBalanceImpact` and `feeImpact` fields.

**Comment by SamKirby22** [comment]
Retest blocked due to new Dashmate issue [to be raised]

**Comment by dashameter** [comment]
retest passed dashmate@.22.12
