### ISSUE TITLE
Setting up local network with dashmate terminates with error: [FAILED] waitForQuorumConnections deadline of 300000 exceeded

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#217]
Setting up a local network using the command `dashmate setup local` terminates prematurely after a long wait, and just at the end of the step: `Create local group configs`. 

## Expected Behavior
Successfully setup local network

## Current Behavior
The process terminates with the error message: `[FAILED] waitForQuorumConnections deadline of 300000 exceeded`

![image](https://user-images.githubusercontent.com/15247893/150649522-68a85733-f091-41d8-9951-bd8d9d33329d.png)

## Steps to Reproduce (for bugs)
`dashmate setup local` 

## Your Environment
* Version used: dashmate@0.21.6-test.2
* Operating System: MacOS (Apple Silicon)

**Comment by dash-maverick** [comment]
@mayoreee can you please retest in v22?

**Comment by mayoreee** [comment]
Passed retest in v22!

Thanks for the fix @dash-maverick
