### ISSUE TITLE
Webpack throws: `Uncaught ReferenceError: require is not defined` on `secp256k1-native` dependency

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#228]
This is about to be merged into monorepo and since I can't file issues on the archive repo I'll file it here:
https://github.com/dashevo/js-dash-sdk/blob/feat/dip15/src/SDK/Client/plugins/DashPay/methods/encryptSharedKey.ts

The `secp256k1-native` dependency is bindings to a native secp256k1 implementation and doesn't run in the browser. The tests in node run fine but webpack won't be able to bundle it. It's important to run all tests via karma in the browser as well.

**Comment by dash-maverick** [comment]
Thanks for the request. It has been moved to the backlog. BTW we will have better QA towards in-browser execution (with the usage of webpack) really soon.

**Comment by dashameter** [comment]
as discussed in the triage today, closing this with fix provdided
