### ISSUE TITLE
Error: InstantLock waiting period for transaction timed out when initializing after funding a new wallet

### ISSUE THREAD

**Issue by HunterSides** [dashevo/platform#245]
## Expected Behavior
After funding a new wallet with tDash a user should be able to initialize and connect to platform.

## Current Behavior
Throws Error: InstantLock waiting period for transaction <insert transaction number> timed out
![image](https://user-images.githubusercontent.com/56932084/153668795-ad2d6084-0894-464b-b059-aac8fff21ad8.png)

## Steps to Reproduce (for bugs)

using this repo https://github.com/HunterSides/DDR-React 
1.  clone & npm install & npm start
2. open localhost:3000 
3. open console & fund wallet address given
4. reload page after funding wallet

## Your Environment

 * @dash-incubator/dapp-sdk": "*"
 * Chrome & Firefox latest
* Windows 10 64 bit
* [Link to your project:](https://github.com/HunterSides/DDR-React )

**Comment by dash-maverick** [comment]
please try reproduce it with latest version (0.21.8) of dashmate - the problem shouldn't appear on that version

**Comment by dashameter** [comment]
> please try reproduce it with latest version (0.21.8) of dashmate - the problem shouldn't appear on that version

@dash-maverick I still get the error, I can't create a new identity

**Comment by dashameter** [comment]
retest passed for dashmate only

**Comment by dash-maverick** [comment]
please retest on testnet

**Comment by HunterSides** [comment]
retest passed - error no longer found
