### ISSUE TITLE
transactionHistory is a unix epoch timestamp instead of a javascript date object

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#264]
In the transactionHistory, the time is stored as a unix epoch timestamp while everywhere else the SDK uses the javascript date object. To be consistent the tx history should also store the time as a date object.

**Comment by dash-maverick** [comment]
https://github.com/dashevo/platform/tree/feat/tx-history-date

**Comment by dashameter** [comment]
retest passed dashmate@.22.12
