### ISSUE TITLE
`identities.topUp()` txs don't show up in the `getTransactionHistory()`

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#290]
It appears the first time a user creates the identity, that credit topup is shown in getTransactionHistory with the utxo `{address: 'false', satoshis: 10000}` however subsequent credit topups via `await getClient().platform?.identities.topUp(identity.id, 1000);` do not show up in the transactionHistory

This was tested on dashmate v.21

**Comment by dash-maverick** [comment]
needs retest with v22

**Comment by dashameter** [comment]
retest passed
