### ISSUE TITLE
identities.register() returns identity with 0 credit balance

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#291]
identity = await client.platform?.identities.register();

returns an identity with balance 0 on v.21 dashmate

I would expect the returned identity to have balance 9997899, the same as returned by identities.get()

Filed here for tracking and retesting once v.22 is released.

**Comment by thephez** [comment]
v.22 does the same. I think it's because the SDK doesn't retrieve the identity at the end of `.register`. If the ST broadcast is succesful, it simply returns the identity that it submitted (see https://github.com/dashevo/platform/blob/v0.22-dev/packages/js-dash-sdk/src/SDK/Client/Platform/methods/identities/register.ts#L33-L45)

**Comment by dash-maverick** [comment]
looks like an issue with State Transition Acknowledgement which JS SDK doesn't fully support yet

**Comment by dash-maverick** [comment]
https://github.com/dashevo/platform/tree/feat/identity-register-balance

**Comment by dashameter** [comment]
temporary workaround is to refetch the identity:

```
identity = await client.platform?.identities.register();

identity = await client.platform?.identities.get(identity.getId()); // TODO remove this line once identities.register() returns correct identity.balance
```

**Comment by dash-maverick** [comment]
retest with v0.22.3 please

**Comment by thephez** [comment]
I'm now receiving a balance when registering identities with v0.22.3 :+1:

**Comment by SamKirby22** [comment]
Retest blocked due to new Dashmate issue [to be raised]

**Comment by thephez** [comment]
v0.22 is on testnet so you can test directly against that without running a dashmate node.

**Comment by dash-maverick** [comment]
Actually that's a point. FYI @jaboski what do you think about that? Can you provide a set of steps that brings a proof the initial issue being fixed?

**Comment by jaboski** [comment]
Yes, I agree with thephez - you can retest that directly on testnet, there is no point to run it on dashmate.
About a set of steps: just follow the instruction in description, e.g.:
`const registeredIdentity = await client.platform.identities.register();
 console.log('Balance: ', registeredIdentity.balance);`

**Comment by jaboski** [comment]
I agree with thephez, you can retest it directly on testnet, there's no point to run it on dashmate.
About steps - just follow the description, e.g.:
`const registeredIdentity = await client.platform.identities.register();
console.log('Balance: ', registeredIdentity.balance);`

**Comment by dashameter** [comment]
retest passed on dashmate@.22.12
