### ISSUE TITLE
Installing v0.22 packages on Apple Silicon throws Error: No native build was found 

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#298]
I’m trying to install packages from the Platform repo [v0.22-dev branch], but got some native build errors for both Node v17 & v16.

## Expected Behavior
Successfully Install from the v0.22-dev branch

## Current Behavior
Throws Error:

- using Node v17:
`Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=102 uv=1 armv=8 libc=glibc node=17.7.0`

- using Node v16:
`Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=93 uv=1 armv=8 libc=glibc node=16.14.0`

`➤ YN0009: │ @dashevo/rs-drive@https://github.com/dashevo/rs-drive.git#commit=186cb24c779c056ace0780457ff751dcd2b49a69 couldn't be built successfully`

## Possible Solution
Generate prebuilds for Apple Silicon running Node 17 and 16

## Steps to Reproduce (for bugs)
`yarn install`

## Your Environment
* Apple Silicon (M1 mac)
* Node v17 & v16

**Comment by pshenmic** [comment]
I think this issue is fixed via merge of https://github.com/dashevo/rs-drive/pull/86

@mayoreee could you confirm if you still facing this issue?

**Comment by mayoreee** [comment]
retest passed. Thank you, @pshenmic!
