### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#307]
Running dashmate commands throws `TypeError: Cannot read properties of undefined`

## Expected Behavior
Successfully run dashmate commands

## Current Behavior
throws error: 
```
 TypeError: Cannot read properties of undefined (reading 'masternodeRewardShares’)
```
## Steps to Reproduce (for bugs)
`dashmate start` or `dashmate stop`

## Your Environment

* Version used: `dashmate v0.22.0`
* Environment name and version: `Node v16.14.2`
* Operating System and version: `darwin-arm64`

**Comment by dash-maverick** [comment]
thanks @markin-io ! FYI @dashameter

**Comment by mayoreee** [comment]
The workaround provided solved this issue. Thanks @markin-io!

**Comment by SamKirby22** [comment]
Reopened as fix still required. As above - resetting Dashamate works in the interim.

**Comment by dash-maverick** [comment]
please retest as the fix has been merged https://github.com/dashevo/platform/pull/310

**Comment by mayoreee** [comment]
Fix passed retest
