### ISSUE TITLE
Listening to events throws an error

### ISSUE THREAD

**Issue by mmick66** [dashevo/platform#377]
I am trying to follow the [official Dash documentation](https://dashevo.github.io/platform/Wallet-library/events/blockheight_changed/) in order to listen to events. 

```
const { Wallet, EVENTS } = require('@dashevo/wallet-lib');

const wallet = new Wallet();

const mnemonic = wallet.exportWallet();
console.log(mnemonic);

wallet.getAccount().then((account) => {
    account.events.on(EVENTS.BLOCKHEIGHT_CHANGED, ({payload: blockHeight})=>{
        console.log(`Blockheight changed to ${blockHeight}`);
    });
    const balance = account.getTotalBalance();
    console.log(`Balance: ${balance}`);
});
```

I get an error:

```
    account.events.on(EVENTS.BLOCKHEIGHT_CHANGED, ({payload: blockHeight})=>{
                   ^

TypeError: Cannot read properties of undefined (reading 'on')
```
which makes sense, as the account object as I see it from the source-code does **not** have an events property. What am I doing wrong?

**Comment by pshenmic** [comment]
Hey there. Sorry, seems like this page is not up to date with recent changes in the SDK. Could you try to subscribe on the account object instead?

For example, this worked for me:
```
account.on(EVENTS.FETCHED_CONFIRMED_TRANSACTION, (tx) =>{
  console.log(tx);
});
```

**Comment by mmick66** [comment]
Thank you. That fixes it. Please update the documentation because there are a number of changes in the codebase which are just not reflected there. Thank you for all the great work by the way!
