### ISSUE TITLE
dashmate setup fails with error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#389]
Setting up `dashmate v0.22.7` after upgrading from `v0.22.3` fails 

## Expected Behavior

Successfully setup `dashmate v0.22.7`

## Current Behavior

Setup fails:
```
✔ Set configuration preset
✔ Set the number of nodes
✔ Enable debug logs
✔ Set the core miner interval
✖ error:0308010C:digital envelope routines::unsupported
◼ Configure Core nodes
◼ Configure Tenderdash nodes
```
## Steps to Reproduce (for bugs)

1. Upgrade `dashmate v0.22.3` to `v0.22.7`
2. Remove all existing associated docker containers, images, and volumes.
3. Run `rm -r ~/.dashmate`
4. Run `dashmate setup local`

## Your Environment

* Version used: `dashmate v0.22.7`  
* Environment name and version: `node-v18.1.0`
* Operating System and version: `darwin-arm64`

**Comment by thephez** [comment]
Does it work correctly for you if you use Node v16? Googling that error seems to indicate an OpenSSL incompatibility when using Node versions > v16. Examples:
https://itsmycode.com/error-digital-envelope-routines-unsupported/
https://github.com/trufflesuite/truffle/issues/4570

**Comment by mayoreee** [comment]
<img width="642" alt="Screenshot 2022-05-24 at 10 33 23" src="https://user-images.githubusercontent.com/15247893/170000405-e908ea29-8d8d-4dba-9e8f-27ccc70ad872.png">

**Comment by pshenmic** [comment]
Node versions other than v16 is not supported at the moment. RIPEMD160 is removed from libssl on Node v18+

**Comment by mayoreee** [comment]
retest passed
