### ISSUE TITLE
Dashmate does not create config dir for current user when installed globally

### ISSUE THREAD

**Issue by strophy** [dashevo/platform#510]
## Expected Behavior

When running globally installed `sudo npm install -g dashmate` as `ubuntu` user, I expect dashmate to create the `/home/ubuntu/.dashmate` dir as necessary.

## Current Behavior

Something is going wrong here: https://github.com/dashevo/platform/blob/v0.23-dev/packages/dashmate/src/ensureHomeDirFactory.js#L20
When I log the value of the two variables in this function, it is clear that it is testing a different directory, failing, and then outputting an error message about a completely different directory.
```
ubuntu@masternode-3:~$ which dashmate
/usr/bin/dashmate
ubuntu@masternode-3:~$ dashmate config
__dirname is /usr/lib/node_modules/dashmate/src
HOME_DIR_PATH is /home/ubuntu/.dashmate
    HomeDirIsNotWritableError: Home dir '/home/ubuntu/.dashmate' is not writeable
ubuntu@masternode-3:~$ ls -lha ~/.dashmate
total 28K
drwxrwxr-x 3 ubuntu ubuntu 4.0K Aug 29 05:48 .
drwxr-x--- 7 ubuntu ubuntu 4.0K Aug 29 06:16 ..
drwxrwxr-x 4 ubuntu ubuntu 4.0K Aug 29 05:48 base
-rw-rw-r-- 1 ubuntu ubuntu  15K Aug 29 05:48 config.json
ubuntu@masternode-3:~$ whoami
ubuntu
```

Why are checking for the writability of `__dirname` and not `HOME_DIR_PATH` instead? Running `dashmate config` when dashmate is globally installed will actually create this directory with the correct owner and group, then incorrectly complain that that owner and group cannot write.

## Possible Solution

Test installing globally
Maybe I am installing globally in the wrong way?

## Steps to Reproduce (for bugs)

https://github.com/dashevo/dash-network-deploy/blob/dashmate/ansible/roles/dashmate/tasks/main.yml

## Context

Using dashmate in deploy tool

## Your Environment

* Version used: 0.23.0-dev.8
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 16.17.0
* Operating System and version (desktop, server, or mobile): Ubuntu 18.04 LTS
* Link to your project: https://github.com/dashevo/dash-network-deploy

**Comment by pshenmic** [comment]
https://github.com/dashevo/platform/pull/537
