### ISSUE TITLE
Revert config values written into config if command failed

### ISSUE THREAD

**Issue by jawid-h** [dashevo/platform#95]
Whenever command that writes values into config fails we end up with a dirty config that prevents subsequent runs of any command. It's then required to run `mn config:reset` which cleans any settings set manually before. And we have to re-set them again.

## Possible Solution

Maybe we can revert values written to a config by a command if it is failed.

## Alternatives Considered

Somehow keep custom set values upon `mn config:reset`, but that would be significantly more complicated to implement.

**Comment by markin-io** [comment]
@jawid-h is this still relevant or we can close it?

**Comment by jaboski** [comment]
@jawid-h said it is not valid anymore and we can close it.
fyi @SamKirby22 @markin-io
