### ISSUE TITLE
Pull bootstrap data to speed up initial sync

### ISSUE THREAD

**Issue by strophy** [dashevo/platform#97]
Syncing testnet is slow. 

## Expected Behavior
Testnet sync is faster

## Current Behavior
Testnet sync is slow

## Possible Solution
It might be faster to pull a `bootstrap.dat` file from https://github.com/UdjinM6/dash-bootstrap to ensure the bottleneck is local node performance and not network.

**Comment by dash-maverick** [comment]
closed because obsolete at this point (dashmate is operating differently at this point)
